name: sigul
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  panorama_viewer: ^2.0.7
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  #dependencias mapa
  flutter_map: ^7.0.1  
  flutter_map_mbtiles: ^1.0.4  
  sqflite: ^2.3.3+1  
  latlong2: ^0.9.1
  path_provider: ^2.1.4 
  mbtiles: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/tiles/
